/**
 * TypeScript 5.4 & Node.js 22/24 Compatibility Shim
 * 
 * This module provides shims and migration helpers for common breaking changes
 * related to the upgrade to TypeScript 5.4 and Node.js 22/24.
 * 
 * Covers:
 *  - Deprecated API replacements (re-exports/wrappers)
 *  - Renamed class/package import shims
 *  - Config format migration
 * 
 * NOTE: This file is autogenerated as part of the migration path. Read all TODOs.
 */

/* ------------------------------------------
 * Deprecated API Replacements
 * ---------------------------------------- */

// Example: Node.js 'fs/promises' APIs remain stable; no breaking API removals here.
// (If any deprecated Node.js APIs are in use, wrap/re-export replacements here.)

// TODO: Review and update any direct usage of legacy 'fs' callback APIs: 
// Node.js 22+ encourages use of promise-based APIs
// Manual migration may be required for custom error handling.


/* ------------------------------------------
 * Import Shims for Renamed Packages/Classes
 * ---------------------------------------- */

// No explicit package/class renames are listed in the context or spec.
// Add aliases below ONLY if target framework/package introduced renames in TS 5.4 or Node.js 22/24.

// Example placeholder for an import alias:
// import { OldClassName as NewClassName } from 'some-package';
// export { NewClassName as OldClassName };
// TODO: If Node.js or TS ecosystem packages used in your codebase renamed exports, add re-exports here.


/* ------------------------------------------
 * Config Format Migration
 * ---------------------------------------- */

/**
 * Transforms old configuration objects into the new config format.
 * Supply the full old config object to get a migrated copy.
 * 
 * For unsupported fields or ambiguous settings, a TODO will be added to the result.
 * 
 * @param oldConfig The configuration object in pre-TS5.4/Node22 format
 * @returns New-format configuration object
 */
export function migrateConfigFormat(oldConfig: any): any {
    const newConfig: any = { ...oldConfig };

    // Example: Node.js 22/24 and newer TS versions have stricter "type" enforcement in package.json.
    // Migrate "module" and "type" fields if present.

    if (oldConfig.module === 'commonjs') {
        // Assume migration to ESM is encouraged
        newConfig.module = 'ESNext';
        newConfig.type = 'module';
        // TODO: Review ESM compatibility for all import/export statements:
        // Node.js 22+ with "type": "module" may require filename extensions in imports.
    }

    // Example: Remove deprecated "esModuleInterop" for projects fully migrated to ESM.
    if ('esModuleInterop' in oldConfig && oldConfig.type === 'module') {
        delete newConfig.esModuleInterop;
        // TODO: Verify that no CJS interop dependencies remain.
    }

    // TODO: If using "target": "ES6" or older, consider upgrading to "ES2020" or newer for Node.js 22+
    if (oldConfig.target && ['ES6', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019'].includes(oldConfig.target)) {
        newConfig.target = 'ES2020';
        // TODO: Ensure your codebase has no usage of deprecated/removed ES features.
    }

    // TODO: If using Yeoman generator blueprints, ensure compatibility with latest Node.js & TS.
    // No changes required here unless custom generator APIs are in use.

    return newConfig;
}

/* ------------------------------------------
 * CI/CD and Docker Build Shims/Reminders
 * ---------------------------------------- */

// TODO: Review all Dockerfiles and CI scripts for ARGs or FROM lines referencing older Node LTS
// E.g. Update "FROM node:18" → "FROM node:22" where appropriate
// Ensure npm and ts-node versions are compatible with Node.js 22/24

// TODO: In Github Actions, update matrix/test runners using 'actions/setup-node' to target '22' or '24' as required

/* ------------------------------------------
 * Application Blueprint Adjustments
 * ---------------------------------------- */

// TODO: Review all scaffolding and blueprints generated for React, Angular, Spring Boot, etc.
// Ensure generated code uses updated config and applies ESM/module/TS5.4 compatibility patterns

/* ------------------------------------------
 * Exports (for import as "@project/compat-shim")
 * ---------------------------------------- */

export default {
    migrateConfigFormat,
    // Any wrapped/re-exported APIs would be added here.
};