/**
 * Core domain types for user profiles.
 */

export interface UserProfile {
  id: string;
  username: string;
  email: string;
  firstName: string;
  lastName: string;
  bio?: string;
  avatarUrl?: string;
  createdAt: Date;
  updatedAt: Date;
}

/** Payload for creating a new profile (id and timestamps are generated by the service). */
export type CreateUserProfilePayload = Omit<UserProfile, 'id' | 'createdAt' | 'updatedAt'>;

/** Payload for updating an existing profile (all fields optional except id). */
export type UpdateUserProfilePayload = Partial<Omit<UserProfile, 'id' | 'createdAt' | 'updatedAt'>>;
